language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - ninja-build
      - llvm-toolchain-trusty-6.0

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja; fi

script:
  - ./cmake_generate.sh build Release
  - cd build
  - ninja
