language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - ninja-build

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake ninja; fi

script:
  - ./cmake_generate.sh build Release
  - cd build
  - ninja
