jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: ShellScript@2
        inputs:
          scriptPath: ./build_linux.sh
  - job: macOS
    pool:
      vmImage: "xcode9-macos10.13"
    steps:
      - task: ShellScript@2
        inputs:
          scriptPath: ./build_mac.sh
  - job: Windows
    pool:
      vmImage: "windows-2019"
    steps:
      - script: |
        pushd "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        for /f "delims=" %%x in ('.\vswhere.exe -latest -property InstallationPath') do set VSPATH=%%x
        popd
        call "%VSPATH%\VC\Auxiliary\Build\vcvarsall.bat" x64
        cmake -G Ninja -DCMAKE_CXX_COMPILER="cl.exe" -DCMAKE_C_COMPILER="cl.exe" -S . -B build
        displayName: Generating with CMake
