jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: ShellScript@2
        inputs:
          scriptPath: ./build_linux.sh
  - job: macOS
    pool:
      vmImage: "macOS-latest"
    steps:
      - task: ShellScript@2
        inputs:
          scriptPath: ./build_mac.sh
