jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - task: ShellScript@2
        inputs:
          scriptPath: ./build_linux.sh
  - job: macOS
    pool:
      vmImage: "xcode12-macOS11.0"
    steps:
      - task: ShellScript@2
        inputs:
          scriptPath: ./build_mac.sh
